# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python3.8 -m venv penv
          source penv/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
      - name: Installing dependencies
        run:  pip install -r requirements.txt
      - name: Training
        run:  python train.py
      - name: Classifying
        run:  python train.py
